export default {
  install (Vue, options) {
    Vue.prototype.$dict = {
      get(key) {
        var lang = options.store.state.lang
        if (key) {
          return this.data[lang][key] ? this.data[lang][key] : '?' + key
        }
        return this.data[lang]
      },
      data: {
        en: {
          'host-content': 'Databases',
          'host-settings': 'Host settings',
          'database-settings': 'Database settings',
          'database-content': 'Tables',
          'database-content-add': 'Add table',
          'table-structure': 'Structure',
          'table-structure-add': 'Add field',
          'table-query': 'SQL Query',
          'table-parameters': 'Settings',
          'table-content': 'Content',
          'table-content-add': 'Add new entry',

          'save': 'Save',
          'load': 'Load',
          'del': 'Delete',
          'copy': 'Save as copy',
          'copy_struct': 'Save as copy structure only',
          'reset': 'Reset',
          'searchpage': 'Filter fields',
          'structure': 'Structure',
          'content': 'Content',
          'settings': 'Settings',
          'back': 'Back',
          'new': 'New',
          'add': 'Add',
          'databases': 'Databases',
          'tables': 'Tables',
          'query': 'SQL-query',
          'answer': 'Answer',
          'send': 'Send',
          'nocols': 'No columns found',
          'norows': 'No rows found',
          'servererror': 'Server responded with error',
          'clickerror': 'Click to close this message, Ctrl (or Shift) + Click to copy',
          'reset_search': 'Reset search',
          'reset_filters': 'Reset filters',
          'reload': 'Reload',
          'logoff': 'Log off',
          'about': 'About',
          'language': 'Language',
          'onpage': 'Results per page',
          'nothingfound': 'Nothing found',
          'filteraside': 'Filter...',
          'first': 'First',
          'truncate': 'Clear table',
          'confirm_action': 'Confirm this action',
          'mutator_done': 'Query completed',
          'server_answer': 'Server answer',
          'mutator_yes': 'Yes, send query',
          'mutator_no': 'No, cancel action',
          'waiting': 'Wating for server response...',
          'th_actions': 'Edit / copy',

        },
        ru: {
          'host-content': 'Базы данных',
          'host-settings': 'Настройки общие',
          'database-settings': 'Настройки базы',
          'database-content': 'Таблицы',
          'database-content-add': 'Новая таблица',
          'table-structure': 'Структура',
          'table-structure-add': 'Добавить поле',
          'table-query': 'Запрос',
          'table-parameters': 'Настройки',
          'table-content': 'Данные',
          'table-content-add': 'Добавить запись',

          'save': 'Сохранить',
          'load': 'Загрузить',
          'del': 'Удалить',
          'copy': 'Сохранить копию',
          'copy_struct': 'Сохранить копию без данных',
          'reset': 'Сбросить',
          'searchpage': 'Искать среди полей',
          'structure': 'Структура',
          'content': 'Данные',
          'settings': 'Настройки',
          'back': 'Назад',
          'new': 'Добавить',
          'add': 'Добавить',
          'databases': 'Базы данных',
          'tables': 'Таблицы',
          'query': 'SQL-запрос',
          'answer': 'Ответ',
          'send': 'Отправить',
          'nocols': 'Не нашлось столбцов',
          'norows': 'Не нашлось строк',
          'servererror': 'Сервер сообщил об ошибке',
          'clickerror': 'Левый клик = закрыть сообщение; Ctrl (или Shift) + клик = копировать и закрыть',
          'reset_search': 'Сбросить',
          'reset_filters': 'Сбросить фильтры',
          'reload': 'Обновить',
          'logoff': 'Выйти',
          'about': 'О программе',
          'language': 'Язык',
          'onpage': 'Записей на страницу',
          'nothingfound': 'Ничего нет',
          'filteraside': 'Найти...',
          'first': 'Первый',
          'truncate': 'Очистить таблицу',
          'confirm_action': 'Подтвердите действие',
          'mutator_done': 'Запрос выполнен',
          'server_answer': 'Ответ сервера',
          'mutator_yes': 'Да, отправить',
          'mutator_no': 'Нет, отменить',
          'waiting': 'Ожидание ответа от сервера...',
          'th_actions': 'Редактировать',
        },
      },

    }
}}